/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as fanIndexRouteImport } from './routes/(fan)/index'
import { Route as fanSpotRouteImport } from './routes/(fan)/spot'
import { Route as fanProfileRouteImport } from './routes/(fan)/profile'
import { Route as fanFollowingRouteImport } from './routes/(fan)/following'
import { Route as fanDiscoverRouteImport } from './routes/(fan)/discover'
import { Route as fanCreateNganyaRouteImport } from './routes/(fan)/create-nganya'
import { Route as fanLayoutRouteImport } from './routes/(fan)/_layout'
import { Route as crewCrewIndexRouteImport } from './routes/(crew)/crew/index'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as fanNganyaSlugRouteImport } from './routes/(fan)/nganya.$slug'
import { Route as crewCrewLayoutRouteImport } from './routes/(crew)/crew/_layout'
import { Route as adminAdminLayoutRouteImport } from './routes/(admin)/admin/_layout'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const fanIndexRoute = fanIndexRouteImport.update({
  id: '/(fan)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const fanSpotRoute = fanSpotRouteImport.update({
  id: '/(fan)/spot',
  path: '/spot',
  getParentRoute: () => rootRouteImport,
} as any)
const fanProfileRoute = fanProfileRouteImport.update({
  id: '/(fan)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const fanFollowingRoute = fanFollowingRouteImport.update({
  id: '/(fan)/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const fanDiscoverRoute = fanDiscoverRouteImport.update({
  id: '/(fan)/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const fanCreateNganyaRoute = fanCreateNganyaRouteImport.update({
  id: '/(fan)/create-nganya',
  path: '/create-nganya',
  getParentRoute: () => rootRouteImport,
} as any)
const fanLayoutRoute = fanLayoutRouteImport.update({
  id: '/(fan)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const crewCrewIndexRoute = crewCrewIndexRouteImport.update({
  id: '/(crew)/crew/',
  path: '/crew/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/(admin)/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const fanNganyaSlugRoute = fanNganyaSlugRouteImport.update({
  id: '/(fan)/nganya/$slug',
  path: '/nganya/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const crewCrewLayoutRoute = crewCrewLayoutRouteImport.update({
  id: '/(crew)/crew/_layout',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminLayoutRoute = adminAdminLayoutRouteImport.update({
  id: '/(admin)/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/create-nganya': typeof fanCreateNganyaRoute
  '/discover': typeof fanDiscoverRoute
  '/following': typeof fanFollowingRoute
  '/profile': typeof fanProfileRoute
  '/spot': typeof fanSpotRoute
  '/': typeof fanIndexRoute
  '/admin': typeof adminAdminLayoutRoute
  '/crew': typeof crewCrewLayoutRoute
  '/nganya/$slug': typeof fanNganyaSlugRoute
  '/admin/': typeof adminAdminIndexRoute
  '/crew/': typeof crewCrewIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/create-nganya': typeof fanCreateNganyaRoute
  '/discover': typeof fanDiscoverRoute
  '/following': typeof fanFollowingRoute
  '/profile': typeof fanProfileRoute
  '/spot': typeof fanSpotRoute
  '/': typeof fanIndexRoute
  '/admin': typeof adminAdminIndexRoute
  '/crew': typeof crewCrewIndexRoute
  '/nganya/$slug': typeof fanNganyaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/(fan)/_layout': typeof fanLayoutRoute
  '/(fan)/create-nganya': typeof fanCreateNganyaRoute
  '/(fan)/discover': typeof fanDiscoverRoute
  '/(fan)/following': typeof fanFollowingRoute
  '/(fan)/profile': typeof fanProfileRoute
  '/(fan)/spot': typeof fanSpotRoute
  '/(fan)/': typeof fanIndexRoute
  '/(admin)/admin/_layout': typeof adminAdminLayoutRoute
  '/(crew)/crew/_layout': typeof crewCrewLayoutRoute
  '/(fan)/nganya/$slug': typeof fanNganyaSlugRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/(crew)/crew/': typeof crewCrewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signup'
    | '/create-nganya'
    | '/discover'
    | '/following'
    | '/profile'
    | '/spot'
    | '/'
    | '/admin'
    | '/crew'
    | '/nganya/$slug'
    | '/admin/'
    | '/crew/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/create-nganya'
    | '/discover'
    | '/following'
    | '/profile'
    | '/spot'
    | '/'
    | '/admin'
    | '/crew'
    | '/nganya/$slug'
  id:
    | '__root__'
    | '/signin'
    | '/signup'
    | '/(fan)/_layout'
    | '/(fan)/create-nganya'
    | '/(fan)/discover'
    | '/(fan)/following'
    | '/(fan)/profile'
    | '/(fan)/spot'
    | '/(fan)/'
    | '/(admin)/admin/_layout'
    | '/(crew)/crew/_layout'
    | '/(fan)/nganya/$slug'
    | '/(admin)/admin/'
    | '/(crew)/crew/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  fanLayoutRoute: typeof fanLayoutRoute
  fanCreateNganyaRoute: typeof fanCreateNganyaRoute
  fanDiscoverRoute: typeof fanDiscoverRoute
  fanFollowingRoute: typeof fanFollowingRoute
  fanProfileRoute: typeof fanProfileRoute
  fanSpotRoute: typeof fanSpotRoute
  fanIndexRoute: typeof fanIndexRoute
  adminAdminLayoutRoute: typeof adminAdminLayoutRoute
  crewCrewLayoutRoute: typeof crewCrewLayoutRoute
  fanNganyaSlugRoute: typeof fanNganyaSlugRoute
  adminAdminIndexRoute: typeof adminAdminIndexRoute
  crewCrewIndexRoute: typeof crewCrewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/': {
      id: '/(fan)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof fanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/spot': {
      id: '/(fan)/spot'
      path: '/spot'
      fullPath: '/spot'
      preLoaderRoute: typeof fanSpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/profile': {
      id: '/(fan)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof fanProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/following': {
      id: '/(fan)/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof fanFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/discover': {
      id: '/(fan)/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof fanDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/create-nganya': {
      id: '/(fan)/create-nganya'
      path: '/create-nganya'
      fullPath: '/create-nganya'
      preLoaderRoute: typeof fanCreateNganyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/_layout': {
      id: '/(fan)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof fanLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(crew)/crew/': {
      id: '/(crew)/crew/'
      path: '/crew'
      fullPath: '/crew/'
      preLoaderRoute: typeof crewCrewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(fan)/nganya/$slug': {
      id: '/(fan)/nganya/$slug'
      path: '/nganya/$slug'
      fullPath: '/nganya/$slug'
      preLoaderRoute: typeof fanNganyaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(crew)/crew/_layout': {
      id: '/(crew)/crew/_layout'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof crewCrewLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin/_layout': {
      id: '/(admin)/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  fanLayoutRoute: fanLayoutRoute,
  fanCreateNganyaRoute: fanCreateNganyaRoute,
  fanDiscoverRoute: fanDiscoverRoute,
  fanFollowingRoute: fanFollowingRoute,
  fanProfileRoute: fanProfileRoute,
  fanSpotRoute: fanSpotRoute,
  fanIndexRoute: fanIndexRoute,
  adminAdminLayoutRoute: adminAdminLayoutRoute,
  crewCrewLayoutRoute: crewCrewLayoutRoute,
  fanNganyaSlugRoute: fanNganyaSlugRoute,
  adminAdminIndexRoute: adminAdminIndexRoute,
  crewCrewIndexRoute: crewCrewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
